application:
  gin_mode: "debug"           # The Gin framework application level must be one of "debug" or "release"
  http_host: "localhost:8080" # The HTTP host this application is listening on, leave empty to not start an HTTP server
  grpc_host: "localhost:9000" # The gRPC host this application is listening on, leave empty to not start a gRPC server
  domain: ""                  # The domain used for the Swagger documentation
