[general]

[store]
[store.primary]
connection = "postgresql://graph-node:let-me-in@host.docker.internal:5432/graph-node"
# connection = "postgresql://graph-node:let-me-in@localhost:5432/graph-node"
weight = 1
pool_size = 10

[chains]
ingestor = "block_ingestor_node"
[chains.holesky-beacon]
protocol = "substreams"
shard = "primary"
provider = [
    { label = "substreams-holesky", details = { type = "substreams", url = "https://holesky-cl.substreams.pinax.network:443", token = "$SUBSTREAMS_API_TOKEN" }},
]

[deployment]
[[deployment.rule]]
shard = "primary"
indexers = [ "default" ]
