name: Build & Push Docker Image

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        go-version: [ 1.21.x ]

    steps:
      - uses: actions/checkout@v3

      - name: Setup SSH Keys and known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_EOSN_DEPLOY_KEY }}"
          git config --global url."git@github.com:pinax-network".insteadOf "https://github.com/pinax-network"
          git config --global url."git@github.com:pomelo-io".insteadOf "https://github.com/pomelo-io"
          git config --global url."git@github.com:eosnationftw".insteadOf "https://github.com/eosnationftw"    

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
          cache: true
          cache-dependency-path: "**go.sum"

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build & Push Docker Image
        env:
          GOPRIVATE: github.com/pinax-network,github.com/eosnationftw,github.com/pomelo-io
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          task build:docker
