# Workflow to build the application and run endpoint tests
name: Build & Tests

on:
  push:
    branches: [ develop*,main ]
  pull_request:
    branches: [ develop*,main ]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [ 1.21.x ]
        os: [ ubuntu-latest ]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
          cache: true
          cache-dependency-path: "**go.sum"

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          cd api-service
          task build
